# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DeMeanInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, x=None):  # noqa: E501
        """DeMeanInput - a model defined in OpenAPI

        :param x: The x of this DeMeanInput.  # noqa: E501
        :type x: float
        """
        self.openapi_types = {
            'x': float
        }

        self.attribute_map = {
            'x': 'x'
        }

        self._x = x

    @classmethod
    def from_dict(cls, dikt) -> 'DeMeanInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The de_mean-input of this DeMeanInput.  # noqa: E501
        :rtype: DeMeanInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self):
        """Gets the x of this DeMeanInput.


        :return: The x of this DeMeanInput.
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this DeMeanInput.


        :param x: The x of this DeMeanInput.
        :type x: float
        """

        self._x = x
