# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InRandomOrderInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """InRandomOrderInput - a model defined in OpenAPI

        :param data: The data of this InRandomOrderInput.  # noqa: E501
        :type data: List[float]
        """
        self.openapi_types = {
            'data': List[float]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InRandomOrderInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The in_random_order-input of this InRandomOrderInput.  # noqa: E501
        :rtype: InRandomOrderInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this InRandomOrderInput.


        :return: The data of this InRandomOrderInput.
        :rtype: List[float]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this InRandomOrderInput.


        :param data: The data of this InRandomOrderInput.
        :type data: List[float]
        """

        self._data = data
