# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class MagnitudeInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, v=None):  # noqa: E501
        """MagnitudeInput - a model defined in OpenAPI

        :param v: The v of this MagnitudeInput.  # noqa: E501
        :type v: List[float]
        """
        self.openapi_types = {
            'v': List[float]
        }

        self.attribute_map = {
            'v': 'v'
        }

        self._v = v

    @classmethod
    def from_dict(cls, dikt) -> 'MagnitudeInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The magnitude-input of this MagnitudeInput.  # noqa: E501
        :rtype: MagnitudeInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def v(self):
        """Gets the v of this MagnitudeInput.


        :return: The v of this MagnitudeInput.
        :rtype: List[float]
        """
        return self._v

    @v.setter
    def v(self, v):
        """Sets the v of this MagnitudeInput.


        :param v: The v of this MagnitudeInput.
        :type v: List[float]
        """

        self._v = v
