# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ShapeInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, mat=None):  # noqa: E501
        """ShapeInput - a model defined in OpenAPI

        :param mat: The mat of this ShapeInput.  # noqa: E501
        :type mat: List[List[float]]
        """
        self.openapi_types = {
            'mat': List[List[float]]
        }

        self.attribute_map = {
            'mat': 'mat'
        }

        self._mat = mat

    @classmethod
    def from_dict(cls, dikt) -> 'ShapeInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The shape-input of this ShapeInput.  # noqa: E501
        :rtype: ShapeInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mat(self):
        """Gets the mat of this ShapeInput.


        :return: The mat of this ShapeInput.
        :rtype: List[List[float]]
        """
        return self._mat

    @mat.setter
    def mat(self, mat):
        """Sets the mat of this ShapeInput.


        :param mat: The mat of this ShapeInput.
        :type mat: List[List[float]]
        """

        self._mat = mat
