FROM data-scratch-amqp-base:latest
USER root
RUN apt-get install -y \
build-essential \
gcc \
python3-dev \
python3-pip

COPY external external
RUN pip3 install --upgrade external/dsl-1.0.0-cp310-cp310-linux_x86_64.whl

COPY requirements.txt .
RUN pip3 install -r requirements.txt

# Set user and group (as declared in base image)
USER 1000:1000
RUN pip3 list