type: object
properties:
  x_train:
    type: array
    items:
      type: array
      items:
        type: number
  x_test:
    type: array
    items:
      type: array
      items:
        type: number
  y_train:
    type: array
    items:
      type: number
  y_test:
    type: array
    items:
      type: number
