post:
  tags: [math]
  operationId: train_test_split
  x-openapi-router-controller: openapi_server.controllers.math_controller
  description: "Description of the endpoint"
  requestBody:
    content:
      application/json:
        schema:
          $ref: "train_test_split-input.yaml"
  responses:
    "200":
      description: "Description of this response."
      content:
        application/json:
          schema:
            $ref: "train_test_split-output.yaml"
