FROM data-scratch-mqtt-base:latest
USER root
RUN apt-get install -y \
build-essential \
gcc \
python3-dev \
python3-pip

COPY external external
RUN pip3 install --upgrade external/dsl-0.0.1-py3-none-any.whl

COPY requirements.txt .
RUN pip3 install -r requirements.txt

# Set user and group (as declared in base image)
USER 1000:1000
