openapi: 3.0.1
info:
  contact:
    email: apiteam@swagger.io
  description: 'This is a sample server Petstore server.  You can find out more about     Swagger
    at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For
    this sample, you can use the api key `special-key` to test the authorization     filters.'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Petstore
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers: [ url: https://petstore.swagger.io/v2, url: http://petstore.swagger.io/v2 ]
tags: 
- name: pet
  description: Everything about your Pets
- name: store
  description: Access to Petstore orders
- name: user
  description: Operations about user
- name: math
  description: Operations about user
  
paths:
  /sqrt:    
    post: 
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/sqrt/post.yaml'      
  /strength:
    post:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/strength/post.yaml'
  /pet:
    post:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/pet/post.yaml'    
    put:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/pet/put.yaml'
  /pet/findByStatus:
    get:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/pet/findByStatus/get.yaml'
  /pet/findByTags:
    get:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/pet/findByTags/get.yaml'
  /pet/{petId}:
    delete:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/pet/{petId}/delete.yaml'
    get:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/pet/{petId}/get.yaml'
    post:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/pet/{petId}/post.yaml'
  /pet/{petId}/uploadImage:
    post:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/pet/{petId}/uploadImage/post.yaml'
  /store/inventory:
    get:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/store/inventory/get.yaml'
  /store/order:
    post:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/store/order/post.yaml'
  /store/order/{orderId}:
    delete:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/store/order/{orderId}/delete.yaml'
    get:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/store/order/{orderId}/get.yaml'
  /user:
    post:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/user/post.yaml'
  /user/createWithArray:
    post:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/user/createWithArray/post.yaml'
  /user/createWithList:
    post:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/user/createWithList/post.yaml'
  /user/login:
    get:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/user/login/get.yaml'
  /user/logout:
    get:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/user/logout/get.yaml'
  /user/{username}:
    delete:
       $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/user/{username}/delete.yaml'
    get:
       $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/user/{username}/get.yaml'
    put:
      $ref: 'file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/paths/user/{username}/put.yaml'
components:
  securitySchemes:
    petstore_auth:
      $ref: "file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/components/securitySchemes/petstore_auth.yaml"
    api_key:
      $ref: "file:///home/thom/repos/base-python-data-science/src/rest-scratch/openapi_server/openapi/components/securitySchemes/api_key.yaml"
