openapi: 3.0.1
info:
  contact:
    email: apiteam@swagger.io
  description:
    "This is a sample server Petstore server.  You can find out more about     Swagger
    at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For
    this sample, you can use the api key `special-key` to test the authorization     filters."
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Petstore
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  [url: https://petstore.swagger.io/v2, url: http://petstore.swagger.io/v2]

tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
  - name: math
    description: Operations about user

paths:
  /sqrt:
    $ref: "paths/sqrt/post.yaml"
  /strength:
    $ref: "paths/strength/post.yaml"
  /pet:
    $ref: "paths/pet/pet.yaml"
  /pet/findByStatus:
    $ref: "paths/pet/findByStatus/findByStatus.yaml"
  /pet/findByTags:
    $ref: "paths/pet/findByTags/findByTags.yaml"
  /pet/{petId}:
    $ref: "paths/pet/{petId}/{petId}.yaml"
  /pet/{petId}/uploadImage:
    $ref: "paths/pet/{petId}/uploadImage/uploadImage.yaml"
  /store/inventory:
    $ref: "paths/store/inventory/inventory.yaml"
  /store/order:
    $ref: "paths/store/order/order.yaml"
  /store/order/{orderId}:
    $ref: "paths/store/order/{orderId}/{orderId}.yaml"
  /user:
    $ref: "paths/user/user.yaml"
  /user/createWithArray:
    $ref: "paths/user/createWithArray/createWithArray.yaml"
  /user/createWithList:
    $ref: "paths/user/createWithList/createWithList.yaml"
  /user/login:
    $ref: "paths/user/login/login.yaml"
  /user/logout:
    $ref: "paths/user/logout/logout.yaml"
  /user/{username}:
    $ref: "paths/user/{username}/{username}.yaml"
components:
  securitySchemes:
    petstore_auth:
      $ref: "components/securitySchemes/petstore_auth.yaml"
    api_key:
      $ref: "components/securitySchemes/api_key.yaml"
