# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class EstimateGradientInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, v=None, h=None):  # noqa: E501
        """EstimateGradientInput - a model defined in OpenAPI

        :param v: The v of this EstimateGradientInput.  # noqa: E501
        :type v: List[float]
        :param h: The h of this EstimateGradientInput.  # noqa: E501
        :type h: float
        """
        self.openapi_types = {
            'v': List[float],
            'h': float
        }

        self.attribute_map = {
            'v': 'v',
            'h': 'h'
        }

        self._v = v
        self._h = h

    @classmethod
    def from_dict(cls, dikt) -> 'EstimateGradientInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The estimate_gradient-input of this EstimateGradientInput.  # noqa: E501
        :rtype: EstimateGradientInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def v(self):
        """Gets the v of this EstimateGradientInput.


        :return: The v of this EstimateGradientInput.
        :rtype: List[float]
        """
        return self._v

    @v.setter
    def v(self, v):
        """Sets the v of this EstimateGradientInput.


        :param v: The v of this EstimateGradientInput.
        :type v: List[float]
        """

        self._v = v

    @property
    def h(self):
        """Gets the h of this EstimateGradientInput.


        :return: The h of this EstimateGradientInput.
        :rtype: float
        """
        return self._h

    @h.setter
    def h(self, h):
        """Sets the h of this EstimateGradientInput.


        :param h: The h of this EstimateGradientInput.
        :type h: float
        """

        self._h = h
