# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class GetColumnInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, mat=None, col=None):  # noqa: E501
        """GetColumnInput - a model defined in OpenAPI

        :param mat: The mat of this GetColumnInput.  # noqa: E501
        :type mat: List[List[float]]
        :param col: The col of this GetColumnInput.  # noqa: E501
        :type col: float
        """
        self.openapi_types = {
            'mat': List[List[float]],
            'col': float
        }

        self.attribute_map = {
            'mat': 'mat',
            'col': 'col'
        }

        self._mat = mat
        self._col = col

    @classmethod
    def from_dict(cls, dikt) -> 'GetColumnInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_column-input of this GetColumnInput.  # noqa: E501
        :rtype: GetColumnInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mat(self):
        """Gets the mat of this GetColumnInput.


        :return: The mat of this GetColumnInput.
        :rtype: List[List[float]]
        """
        return self._mat

    @mat.setter
    def mat(self, mat):
        """Sets the mat of this GetColumnInput.


        :param mat: The mat of this GetColumnInput.
        :type mat: List[List[float]]
        """

        self._mat = mat

    @property
    def col(self):
        """Gets the col of this GetColumnInput.


        :return: The col of this GetColumnInput.
        :rtype: float
        """
        return self._col

    @col.setter
    def col(self, col):
        """Sets the col of this GetColumnInput.


        :param col: The col of this GetColumnInput.
        :type col: float
        """

        self._col = col
