# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class GetRowInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, mat=None, row=None):  # noqa: E501
        """GetRowInput - a model defined in OpenAPI

        :param mat: The mat of this GetRowInput.  # noqa: E501
        :type mat: List[List[float]]
        :param row: The row of this GetRowInput.  # noqa: E501
        :type row: float
        """
        self.openapi_types = {
            'mat': List[List[float]],
            'row': float
        }

        self.attribute_map = {
            'mat': 'mat',
            'row': 'row'
        }

        self._mat = mat
        self._row = row

    @classmethod
    def from_dict(cls, dikt) -> 'GetRowInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_row-input of this GetRowInput.  # noqa: E501
        :rtype: GetRowInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mat(self):
        """Gets the mat of this GetRowInput.


        :return: The mat of this GetRowInput.
        :rtype: List[List[float]]
        """
        return self._mat

    @mat.setter
    def mat(self, mat):
        """Sets the mat of this GetRowInput.


        :param mat: The mat of this GetRowInput.
        :type mat: List[List[float]]
        """

        self._mat = mat

    @property
    def row(self):
        """Gets the row of this GetRowInput.


        :return: The row of this GetRowInput.
        :rtype: float
        """
        return self._row

    @row.setter
    def row(self, row):
        """Sets the row of this GetRowInput.


        :param row: The row of this GetRowInput.
        :type row: float
        """

        self._row = row
