# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class MatrixAddInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, mat1=None, mat2=None):  # noqa: E501
        """MatrixAddInput - a model defined in OpenAPI

        :param mat1: The mat1 of this MatrixAddInput.  # noqa: E501
        :type mat1: List[List[float]]
        :param mat2: The mat2 of this MatrixAddInput.  # noqa: E501
        :type mat2: List[List[float]]
        """
        self.openapi_types = {
            'mat1': List[List[float]],
            'mat2': List[List[float]]
        }

        self.attribute_map = {
            'mat1': 'mat1',
            'mat2': 'mat2'
        }

        self._mat1 = mat1
        self._mat2 = mat2

    @classmethod
    def from_dict(cls, dikt) -> 'MatrixAddInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The matrix_add-input of this MatrixAddInput.  # noqa: E501
        :rtype: MatrixAddInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mat1(self):
        """Gets the mat1 of this MatrixAddInput.


        :return: The mat1 of this MatrixAddInput.
        :rtype: List[List[float]]
        """
        return self._mat1

    @mat1.setter
    def mat1(self, mat1):
        """Sets the mat1 of this MatrixAddInput.


        :param mat1: The mat1 of this MatrixAddInput.
        :type mat1: List[List[float]]
        """

        self._mat1 = mat1

    @property
    def mat2(self):
        """Gets the mat2 of this MatrixAddInput.


        :return: The mat2 of this MatrixAddInput.
        :rtype: List[List[float]]
        """
        return self._mat2

    @mat2.setter
    def mat2(self, mat2):
        """Sets the mat2 of this MatrixAddInput.


        :param mat2: The mat2 of this MatrixAddInput.
        :type mat2: List[List[float]]
        """

        self._mat2 = mat2
