# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class PartialDifferenceQuotientInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, v=None, i=None, h=None):  # noqa: E501
        """PartialDifferenceQuotientInput - a model defined in OpenAPI

        :param v: The v of this PartialDifferenceQuotientInput.  # noqa: E501
        :type v: List[float]
        :param i: The i of this PartialDifferenceQuotientInput.  # noqa: E501
        :type i: object
        :param h: The h of this PartialDifferenceQuotientInput.  # noqa: E501
        :type h: object
        """
        self.openapi_types = {
            'v': List[float],
            'i': object,
            'h': object
        }

        self.attribute_map = {
            'v': 'v',
            'i': 'i',
            'h': 'h'
        }

        self._v = v
        self._i = i
        self._h = h

    @classmethod
    def from_dict(cls, dikt) -> 'PartialDifferenceQuotientInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The partial_difference_quotient-input of this PartialDifferenceQuotientInput.  # noqa: E501
        :rtype: PartialDifferenceQuotientInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def v(self):
        """Gets the v of this PartialDifferenceQuotientInput.

        vector  # noqa: E501

        :return: The v of this PartialDifferenceQuotientInput.
        :rtype: List[float]
        """
        return self._v

    @v.setter
    def v(self, v):
        """Sets the v of this PartialDifferenceQuotientInput.

        vector  # noqa: E501

        :param v: The v of this PartialDifferenceQuotientInput.
        :type v: List[float]
        """

        self._v = v

    @property
    def i(self):
        """Gets the i of this PartialDifferenceQuotientInput.


        :return: The i of this PartialDifferenceQuotientInput.
        :rtype: object
        """
        return self._i

    @i.setter
    def i(self, i):
        """Sets the i of this PartialDifferenceQuotientInput.


        :param i: The i of this PartialDifferenceQuotientInput.
        :type i: object
        """

        self._i = i

    @property
    def h(self):
        """Gets the h of this PartialDifferenceQuotientInput.


        :return: The h of this PartialDifferenceQuotientInput.
        :rtype: object
        """
        return self._h

    @h.setter
    def h(self, h):
        """Sets the h of this PartialDifferenceQuotientInput.


        :param h: The h of this PartialDifferenceQuotientInput.
        :type h: object
        """

        self._h = h
