type: object
properties:
  x:
    type: array
    items:
      type: array
      items:
        type: number
  y:
    type: array
    items:
      type: array
      items:
        type: number
  p:
    type: number