FROM data-scratch-library-base:1.0.0 AS builder
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    python3-dev \
    python3-pip && \
    rm -rf /var/lib/apt/lists/*
COPY requirements.txt /usr/src/app/requirements.txt
WORKDIR /usr/src/app
RUN pip3 install --no-cache-dir --only-binary :all: -r requirements.txt