FROM data-scratch-library-base:latest as builder
USER root
RUN apt-get update #&& apt-get install -y xz-utils ca-certificates
RUN apt-get install -y \
build-essential \
gcc \
python3-dev \
python3-pip
COPY requirements.txt /usr/src/app/requirements.txt
WORKDIR /usr/src/app
RUN pip3 install -r requirements.txt