openapi: 3.0.1
info:
  contact:
    email: apiteam@swagger.io
  description:
    "This is a sample server Petstore server.  You can find out more about     Swagger
    at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For
    this sample, you can use the api key `special-key` to test the authorization     filters."
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Petstore
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  [url: https://petstore.swagger.io/v2, url: http://petstore.swagger.io/v2]

tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
  - name: math
    description: Operations about user

paths:
  /sqrt:
    $ref: "paths/sqrt/sqrt.yaml"
  /strength:
    $ref: "paths/strength/strength.yaml"
  /accuracy:
    $ref: "paths/accuracy/accuracy.yaml"
  /bucketize:
    $ref: "paths/bucketize/bucketize.yaml"
  /correlation:
    $ref: "paths/correlation/correlation.yaml"
  /correlation_matrix:
    $ref: "paths/correlation_matrix/correlation_matrix.yaml"
  /covariance:
    $ref: "paths/covariance/covariance.yaml"
  /data_range:
    $ref: "paths/data_range/data_range.yaml"
  /de_mean:
    $ref: "paths/de_mean/de_mean.yaml"
  /difference_quotient:
    $ref: "paths/difference_quotient/difference_quotient.yaml"
  /distance:
    $ref: "paths/distance/distance.yaml"
  /dot:
    $ref: "paths/dot/dot.yaml"
  /echo:
    $ref: "paths/echo/echo.yaml"
  /estimate_gradient:
    $ref: "paths/estimate_gradient/estimate_gradient.yaml"
  /f1_score:
    $ref: "paths/f1_score/f1_score.yaml"
  /get_column:
    $ref: "paths/get_column/get_column.yaml"
  /get_row:
    $ref: "paths/get_row/get_row.yaml"
  /in_random_order:
    $ref: "paths/in_random_order/in_random_order.yaml"
  /interquartile_range:
    $ref: "paths/interquartile_range/interquartile_range.yaml"
  /magnitude:
    $ref: "paths/magnitude/magnitude.yaml"
  /matrix_add:
    $ref: "paths/matrix_add/matrix_add.yaml"
  /maximize_batch:
    $ref: "paths/maximize_batch/maximize_batch.yaml"
  /maximize_stochastic:
    $ref: "paths/maximize_stochastic/maximize_stochastic.yaml"
  /mean:
    $ref: "paths/mean/mean.yaml"
  /median:
    $ref: "paths/median/median.yaml"
  /minimize_batch:
    $ref: "paths/minimize_batch/minimize_batch.yaml"
  /minimize_stochastic:
    $ref: "paths/minimize_stochastic/minimize_stochastic.yaml"
  /mode:
    $ref: "paths/mode/mode.yaml"
  /partial_difference_quotient:
    $ref: "paths/partial_difference_quotient/partial_difference_quotient.yaml"
  /precision:
    $ref: "paths/precision/precision.yaml"
  /quantile:
    $ref: "paths/quantile/quantile.yaml"
  /recall:
    $ref: "paths/recall/recall.yaml"
  /scalar_multiply:
    $ref: "paths/scalar_multiply/scalar_multiply.yaml"
  /shape:
    $ref: "paths/shape/shape.yaml"
  /split_data:
    $ref: "paths/split_data/split_data.yaml"
  /squared_distance:
    $ref: "paths/squared_distance/squared_distance.yaml"
  /standard_deviation:
    $ref: "paths/standard_deviation/standard_deviation.yaml"
  /sum_of_squares:
    $ref: "paths/sum_of_squares/sum_of_squares.yaml"
  /train_test_split:
    $ref: "paths/train_test_split/train_test_split.yaml"
  /variance:
    $ref: "paths/variance/variance.yaml"
  /vector_add:
    $ref: "paths/vector_add/vector_add.yaml"
  /vector_mean:
    $ref: "paths/vector_mean/vector_mean.yaml"
  /vector_subtract:
    $ref: "paths/vector_subtract/vector_subtract.yaml"
  /vector_sum:
    $ref: "paths/vector_sum/vector_sum.yaml"
  /pet:
    $ref: "paths/pet/pet.yaml"
  /pet/findByStatus:
    $ref: "paths/pet/findByStatus.yaml"
  /pet/findByTags:
    $ref: "paths/pet/findByTags.yaml"
  /pet/{petId}:
    $ref: "paths/pet/{petId}.yaml"
  /pet/{petId}/uploadImage:
    $ref: "paths/pet/uploadImage.yaml"
  /store/inventory:
    $ref: "paths/store/inventory.yaml"
  /store/order:
    $ref: "paths/store/order.yaml"
  /store/order/{orderId}:
    $ref: "paths/store/{orderId}.yaml"
  /user:
    $ref: "paths/user/user.yaml"
  /user/createWithArray:
    $ref: "paths/user/createWithArray.yaml"
  /user/createWithList:
    $ref: "paths/user/createWithList.yaml"
  /user/login:
    $ref: "paths/user/login.yaml"
  /user/logout:
    $ref: "paths/user/logout.yaml"
  /user/{username}:
    $ref: "paths/user/{username}.yaml"
components:
  securitySchemes:
    petstore_auth:
      $ref: "components/securitySchemes/petstore_auth.yaml"
    api_key:
      $ref: "components/securitySchemes/api_key.yaml"
